 ---
title: "SD22.8.6"
author: "Shoumit Dey"
date: "08/04/2024"
output: html_document
---
1. Load packages
2. Set paths
```{r message=FALSE}
#Load packages
library(Seurat)
library(EnhancedVolcano)
library(sqldf)
library(dplyr)
library(corrplot)
library(reshape2)
#define study path
save_path <- "add/your/path/here"
setwd(save_path)

if (!file.exists(paste0(getwd(), "/R"))){
  dir.create(paste0(getwd(), "/R"))
}

save_path <- paste0(getwd(), "/R/")

#create sub-directories
if (!file.exists(paste0(save_path, "markers"))){
  dir.create(paste0(save_path, "markers"))
}
dir.create(paste0(save_path, "markers"))

```
Load pre-processed objects
```{r read_RDS_if_available}
# Start the clock!
ptm <- proc.time()
#read files
res=0.3
dims=15
integrated_LC_cohort1 <- readRDS(paste0(save_path, "partial_dims_",dims,"_res_",res,"_LC_cohort1.Rds"))
subclust_dims <- 10
subclust_res <- 0.2
cluster2only <- readRDS(paste0(save_path, "lesion_core_dims_",subclust_dims,"_res_",subclust_res,".rds"))
cyto_dims=10
cyto_res=0.5
cluster2CytoOnly <- readRDS(paste0(save_path,"lesion_core_cyto_only_dims_",cyto_dims,"_res_",cyto_res,".Rds"))
cluster2CytoOnly_meta <- data.frame(cluster2CytoOnly@meta.data[, c("cyto_cluster")],row.names = rownames(cluster2CytoOnly@meta.data))
# Stop the clock and print time taken
time_taken<- proc.time() - ptm
print(paste0("Time elapsed: ", sprintf((time_taken[3]/60), fmt = '%#.2f')," minutes"))

```
Plotting Figures 5a, b, c and d
```{r plotting_umap_clusters}
# Start the clock!
ptm <- proc.time()
#Plotting Figure 5b Extended Data Figure 8d-f
pdf(paste0(save_path, "SpatialDimPlot_PC1to",dims,"res",res,".pdf"))
  x<-SpatialDimPlot(integrated_LC_cohort1, image.alpha = 0, crop = FALSE, pt.size.factor = 1)
  for(i in 1:12){
    fig1<-x[[i]]
    print(fig1)
  }
  rm(x)
dev.off() 
#Plotting Figure 5a, Extended Data Figure 8b and c
pdf(paste0(save_path, "Figure 5a8bc.pdf"))
  #Plotting Figure 5a
  DimPlot(integrated_LC_cohort1, reduction = "tsne", split.by = "group")
  #Plotting Extended Data Figure 8b
  DimPlot(integrated_LC_cohort1, reduction = "tsne", label = TRUE) + NoLegend() 
  #Plotting Extended Data Figure 8c
  DimPlot(integrated_LC_cohort1, reduction = "tsne", group.by = "orig.ident")
dev.off()
#PLotting Figure 5b
pdf(paste0(save_path, "Fig5b.pdf"), height = 5, width = 15)
  SpatialDimPlot(integrated_LC_cohort1, images = c("LC_403_1C2","LC_403_1L1"), crop = F, ncol = 2, image.alpha = 0)
dev.off()
#PLotting Extended Data Figure 9a
pdf(paste0(save_path, "Fig5c.pdf"), height = 5, width = 20)
  SpatialFeaturePlot(integrated_LC_cohort1, images = "LC_403_1C2", features = c("KRT5","LOR","LYZ","S100A2","TNF","IFNG","IL10","IL1B"), crop = F, ncol = 2, image.alpha = 0, alpha = c(0,0.7), pt.size.factor = 1)
dev.off()
# Stop the clock and print time taken
time_taken<- proc.time() - ptm
print(paste0("Time elapsed: ", sprintf((time_taken[3]/60), fmt = '%#.2f')," minutes"))
```
DE BY SEURAT CLUSTERS (WILCOXON RANK SUM)
```{r differential_expresion}
# Start the clock!
ptm <- proc.time()
#If not pre-run already
integrated_LC_cohort1 <- PrepSCTFindMarkers(integrated_LC_cohort1, assay = "SCT")
#find markers - method Wilcoxon rank sum, looking at positive markers ie
#upregulated genes in each cluster with a minimum number of spots expressing
#the said gene as 25%. Log2fold change threshold at 0.25 
all_markers <- FindAllMarkers(integrated_LC_cohort1, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25, assay = "SCT")
#save marker genes
write.csv(all_markers, paste0(save_path, "/markers/","markers_dims",dims,"_res",res,".csv"), row.names = TRUE)
#read marker genes
all_markers <- read.csv(paste0(save_path, "/markers/","markers_dims",dims,"_res",res,".csv"), header = TRUE)
#find markers bite site versus lesion 
#Method: Wilcoxon rank sum, looking at positive markers ie
#upregulated genes in each cluster with a minimum number of spots expressing
#the said gene as 25%. Log2fold change threshold at 0.25 
dermis7vs2 <- FindMarkers(integrated_LC_cohort1, ident.1 = c(7), ident.2 = c(2))
#save marker genes
write.csv(dermis7vs2, paste0(save_path, "/markers/biteVslesion.csv"), row.names = TRUE)
#read marker genes
dermis7vs2 <- read.csv(paste0(save_path, "/markers/biteVslesion.csv"), header = TRUE)
#define a dataframe for volcano plot  
df <- dermis7vs2
#df$gene <- rownames(df)
df$p_val <- NULL
#reformat column names
colnames(df) <- c("gene","log2FoldChange","pct1","pct2","pvalue")
#setting a very small number in lieu of zero p-value
df$pvalue[df$pvalue==0]<-5e-305
#adding gene names as rownames 
df$gene <- rownames(df) 

#Plotting figure 5g
pdf(paste0(save_path, "Fig5g.pdf"), height = 12, width = 8)
      print(EnhancedVolcano(df,
                      lab = rownames(df),
                      x = 'log2FoldChange',
                      xlim = c(-1.5, 1.5),
                      ylim = c(0,350),
                      y = 'pvalue',
                      title = "dermis7vs2",
                      pCutoff = 10e-5,
                      FCcutoff = 0.5,
                      pointSize = 1,
                      labSize = 5, 
                      subtitle = "",
                      drawConnectors = TRUE,
                      widthConnectors = 0.25)
  )
dev.off()
#Plotting Extended data figure 8a
pdf(paste0(save_path, "heatmap_overall_clustering.pdf"), height = 10, width = 15)
  DefaultAssay(integrated_LC_cohort1) <- "SCT"
  integrated_LC_cohort1<-SetIdent(integrated_LC_cohort1, value = "seurat_clusters")
  all_markers %>%
      group_by(cluster) %>%
      top_n(n = 5, wt = avg_log2FC) -> top5
  DoHeatmap(integrated_LC_cohort1, features = top5$gene) + NoLegend()
dev.off()

# Stop the clock and print time taken
time_taken<- proc.time() - ptm
print(paste0("Time elapsed: ", sprintf((time_taken[3]/60), fmt = '%#.2f')," minutes"))
```

```{r Fig6}
# Start the clock!
ptm <- proc.time()
#PLotting Figure 6a
pdf(paste0(save_path, "Fig6a.pdf"), height = 5, width = 7)
  SpatialDimPlot(cluster2only, images = "LC_403_1C2", crop = F, ncol = 1, image.alpha = 0.6, group.by = "seurat_clusters", pt.size.factor = 1.2)
dev.off()
#PLotting Figure 6b
pdf(paste0(save_path, "cluster2only_markers.pdf"), height = 3, width = 7)
  DotPlot(cluster2only, features = c("CXCL9","CCL21","KRT1","CCL22","ACTA2","CCL19","IGKC","IGFBP7","GREM1","MMP2","PI16","COL1A1","FBP1","MT1G","NUPR1","CHI3L1"), group.by = "seurat_clusters", cols = c("grey","red")) + RotatedAxis()
dev.off()
#PLotting Figure 6c-f
pdf(paste0(save_path, "Fig6cdef.pdf"), height = 5, width = 20)
  SpatialFeaturePlot(integrated_LC_cohort1, images = "LC_403_1C2", features = c("CXCL9","CCL19","MMP2","CHI3L1"), crop = F, ncol = 4, image.alpha = 0, alpha = c(0,0.7), pt.size.factor = 1)
dev.off()
# Stop the clock and print time taken
time_taken<- proc.time() - ptm
print(paste0("Time elapsed: ", sprintf((time_taken[3]/60), fmt = '%#.2f')," minutes"))
```

HEALTHY Vs LESION
```{r selecting_healthy_spots}
#barcode labels
#"402_3C1","402_3C2","402_3L1-3","402_3R1-4","403_1C1","403_1C2","403_1L1-7","403_1L2-8","013_8C1", "013_8C2", "013_8L1-11", "013_8R1-12"

healthy_1l1 <- read.csv(paste0(save_path, "1L1_healthy.csv"), header = T)
healthy_1l1$Barcode <- paste0(healthy_1l1$Barcode, "_7")
colnames(healthy_1l1) <- c("barcodes","spot_annot")

healthy_1l2 <- read.csv(paste0(save_path, "1L2_healthy.csv"), header = T)
healthy_1l2$Barcode <- paste0(healthy_1l2$Barcode, "_8")
colnames(healthy_1l2) <- c("barcodes","spot_annot")

healthy_3l1 <- read.csv(paste0(save_path, "3L1_healthy.csv"), header = T)
healthy_3l1$Barcode <- paste0(healthy_3l1$Barcode, "_3")
colnames(healthy_3l1) <- c("barcodes","spot_annot")

healthy_3r1 <- read.csv(paste0(save_path, "3R1_healthy.csv"), header = T)
healthy_3r1$Barcode <- paste0(healthy_3r1$Barcode, "_4")
colnames(healthy_3r1) <- c("barcodes","spot_annot")

healthy_8l1 <- read.csv(paste0(save_path, "8L1_healthy.csv"), header = T)
healthy_8l1$Barcode <- paste0(healthy_8l1$Barcode, "_11")
colnames(healthy_8l1) <- c("barcodes","spot_annot")

healthy_8r1 <- read.csv(paste0(save_path, "8R1_healthy.csv"), header = T)
healthy_8r1$Barcode <- paste0(healthy_8r1$Barcode, "_12")
colnames(healthy_8r1) <- c("barcodes","spot_annot")

all_healthy_spots <- rbind(healthy_1l1, healthy_1l2, healthy_3l1, healthy_3r1, healthy_8l1, healthy_8r1)
colnames(all_healthy_spots) <- c("barcodes","lesion_health")

meta_current <- integrated_LC_cohort1@meta.data
meta_current$barcodes <- rownames(meta_current)

meta_minus_all_healthy <- subset(meta_current, subset = !barcodes %in% all_healthy_spots$barcodes)
meta_minus_all_healthy$lesion_health <- as.character(meta_minus_all_healthy$group)
meta_minus_all_healthy$lesion_health[meta_minus_all_healthy$lesion_health == "healthy"] <- "adjacent"
meta_minus_all_healthy <- meta_minus_all_healthy[, c("barcodes","lesion_health")]

new_meta <- rbind(all_healthy_spots, meta_minus_all_healthy)
rownames(new_meta) <- new_meta$barcodes

integrated_LC_cohort1 <- AddMetaData(integrated_LC_cohort1, metadata = new_meta)
#use this for cytokine clusters
meta_health <- data.frame(integrated_LC_cohort1$lesion_health)

pdf(paste0(save_path, "re_drawn_healthy_vs_lesion_annotation.pdf"), height = 10, width=15)
  SpatialDimPlot(integrated_LC_cohort1, group.by = "lesion_health", ncol = 4, crop = F, pt.size.factor = 1.5)
dev.off()


Idents(integrated_LC_cohort1) <- "lesion_health"

reduced_integrated_LC_cohort1 <- subset(integrated_LC_cohort1, subset = lesion_health == "adjacent", invert=T)

###fetch seurat cluster colours
p <- DimPlot(reduced_integrated_LC_cohort1) # Generate the tSNE plot, but save it as an object
pbuild <- ggplot2::ggplot_build(p) # Use ggplot_build to deconstruct the ggplot object
pdata <- pbuild$data[[1]] # Pull the data used for the plot
pdata <-  pdata[order(pdata$group), ] # Order the plot data by group
ucols <- unique(pdata$colour) # Get a vector of unique colors
names(ucols) <- unique(pdata$group) # Add the groups to the vector of colors as names


lesion_health_prop_by_cluster <- prop.table(table(reduced_integrated_LC_cohort1$integrated_snn_res.0.3, reduced_integrated_LC_cohort1$lesion_health), margin = 2)
lesion_health_prop_by_cluster

samples_prop_by_cluster <- prop.table(table(reduced_integrated_LC_cohort1$orig.ident, reduced_integrated_LC_cohort1$integrated_snn_res.0.3), margin = 2)
samples_prop_by_cluster

pdf(paste0(save_path, "new_Fig5d.pdf"), height = 10, width=5)
  barplot(lesion_health_prop_by_cluster, 
          col=ucols , 
          border="white", 
          space=0.04, 
          font.axis=2)
  p
dev.off()

ccls_ils_tnfs<-c(grep("^CCL", rownames(reduced_integrated_LC_cohort1),value = T), grep("^CXC", rownames(reduced_integrated_LC_cohort1),value = T), grep("^TNF", rownames(reduced_integrated_LC_cohort1),value = T), grep("^IL", rownames(reduced_integrated_LC_cohort1),value = T), grep("^IFN", rownames(reduced_integrated_LC_cohort1),value = T))

reduced_integrated_LC_cohort1 <- PrepSCTFindMarkers(reduced_integrated_LC_cohort1, assay = "SCT")
Idents(reduced_integrated_LC_cohort1) <- "lesion_health"
all_lesion_health_markers <- FindAllMarkers(reduced_integrated_LC_cohort1, min.pct = 0.25, logfc.threshold = 0.25, assay = "SCT", features = ccls_ils_tnfs)
Idents(integrated_LC_cohort1) <- "integrated_snn_res.0.3"
integrated_LC_cohort1 <- PrepSCTFindMarkers(integrated_LC_cohort1, assay = "SCT")
all_cyto_lesioncore_bite_markers <- FindMarkers(integrated_LC_cohort1, ident.1 = "2",ident.2 = "7", min.pct = 0.25, logfc.threshold = 0.25, assay = "SCT", features = ccls_ils_tnfs)

Idents(reduced_integrated_LC_cohort1) <- "integrated_snn_res.0.3"


pdf(paste0(save_path, "new_ExtData10_health_lesion.pdf"), height = 4, width=6)
  DotPlot(reduced_integrated_LC_cohort1, features = unique(all_lesion_health_markers$gene), group.by = "lesion_health", assay = "SCT") + coord_flip()
dev.off()
pdf(paste0(save_path, "new_ExtData10_bite_lesion.pdf"), height = 8, width=6)
  DotPlot(integrated_LC_cohort1, features = rownames(all_cyto_lesioncore_bite_markers), group.by = "seurat_clusters", assay = "SCT", idents = c(2,7)) + coord_flip()
dev.off()
```




Figure 6g,h,i&j
```{r cytokine_cluster}
# Start the clock!
ptm <- proc.time()

#Figure 6g
#Include meta data information here
cluster2CytoOnly<-AddMetaData(cluster2CytoOnly, metadata = meta_health)
cluster2CytoOnly_health_lesion <- subset(cluster2CytoOnly, subset = integrated_LC_cohort1.lesion_health == "adjacent", invert = T)
pdf(paste0(save_path,"Fig6g_new.pdf"), width = 4, height = 3)
  umap_ccls_ils_tnfs_by_group<-DimPlot(cluster2CytoOnly_health_lesion, reduction = "umap", label = F, split.by = "integrated_LC_cohort1.lesion_health", group.by = "cyto_cluster") + ggtitle(label = "")
  print(umap_ccls_ils_tnfs_by_group)
dev.off()  

#Figure 6h

###fetch seurat cluster colours
p <- DimPlot(cluster2CytoOnly_health_lesion) # Generate the tSNE plot, but save it as an object
pbuild <- ggplot2::ggplot_build(p) # Use ggplot_build to deconstruct the ggplot object
pdata <- pbuild$data[[1]] # Pull the data used for the plot
pdata <-  pdata[order(pdata$group), ] # Order the plot data by group
ucols <- unique(pdata$colour) # Get a vector of unique colors
names(ucols) <- unique(pdata$group) # Add the groups to the vector of colors as names


table(cluster2CytoOnly_health_lesion$integrated_LC_cohort1.lesion_health, cluster2CytoOnly_health_lesion$cyto_cluster)
lesion_health_prop_by_cyto_cluster<-prop.table(table(cluster2CytoOnly_health_lesion$cyto_cluster,cluster2CytoOnly_health_lesion$integrated_LC_cohort1.lesion_health), margin = 2)
orig_prop_by_cyto_cluster<-prop.table(table(cluster2CytoOnly_health_lesion$cyto_cluster,cluster2CytoOnly_health_lesion$orig.ident), margin = 2)

# samples_prop_by_cluster <- prop.table(table(reduced_integrated_LC_cohort1$orig.ident, reduced_integrated_LC_cohort1$integrated_snn_res.0.3), margin = 2)
# samples_prop_by_cluster

pdf(paste0(save_path, "new_Fig6h.pdf"), height = 10, width=5)
  barplot(lesion_health_prop_by_cyto_cluster, 
          col=ucols , 
          border="white", 
          space=0.04, 
          font.axis=2)
  barplot(orig_prop_by_cyto_cluster, 
        col=ucols , 
        border="white", 
        space=0.04, 
        font.axis=2)
  p
dev.off()
################################

#Figure 6i
pdf(paste0(save_path, "Fig6i.pdf"), height = 5, width = 7)
  SpatialDimPlot(cluster2CytoOnly, images = "LC_403_1C1", crop = F, ncol = 1, image.alpha = 0.6, group.by = "cyto_cluster", pt.size.factor = 1.2)
  SpatialDimPlot(cluster2CytoOnly, images = "LC_403_1C2", crop = F, ncol = 1, image.alpha = 0.6, group.by = "cyto_cluster", pt.size.factor = 1.2)
  SpatialDimPlot(cluster2CytoOnly, images = "LC_402_3C1", crop = F, ncol = 1, image.alpha = 0.6, group.by = "cyto_cluster", pt.size.factor = 1.2)
  SpatialDimPlot(cluster2CytoOnly, images = "LC_402_3C2", crop = F, ncol = 1, image.alpha = 0.6, group.by = "cyto_cluster", pt.size.factor = 1.2)
  SpatialDimPlot(cluster2CytoOnly, images = "LC_013_8C1", crop = F, ncol = 1, image.alpha = 0.6, group.by = "cyto_cluster", pt.size.factor = 1.2)
  SpatialDimPlot(cluster2CytoOnly, images = "LC_013_8C2", crop = F, ncol = 1, image.alpha = 0.6, group.by = "cyto_cluster", pt.size.factor = 1.2)
dev.off()

#Switch to normalised assay for calucalting DE genes
DefaultAssay(cluster2CytoOnly)<-"SCT"
#Set idents as clusters obtained using cytokine etc genes
#as described in prepare_rds.Rmd
Idents(cluster2CytoOnly)<-"cyto_cluster"
cluster2CytoOnly<-PrepSCTFindMarkers(cluster2CytoOnly)
all_lesion_cyto_cluster_markers<-FindAllMarkers(cluster2CytoOnly, features = ccls_ils_tnfs)
#markers saved here
write.csv(all_lesion_cyto_cluster_markers,paste0(save_path,"markers/core_lesion_cyto_cluster_markers.csv"), row.names = F)
#Cyto0:CCL18,CXCL13,CCL22,IL4I1
#Cyto1:CXCL10,CXCL9,CXCL11,IL7R
#Cyto2:CCL5,IL2RG,IL16,ILF3,CXCR3
#Cyto3:'NA'
#Cyto4:CXCL12,CXCL14,CCL19,CCL13
#Cyto5:CXCL14,CXCL12

#Figure 6j
pdf(paste0(save_path,"Fig6j.pdf"), width = 7, height = 3)
    DotPlot(cluster2CytoOnly, features = c("CCL18","CXCL13","CCL22","IL4I1","CXCL10","CXCL9","CXCL11","IL7R","CCL5","IL2RG","IL16","ILF3","CXCR3","CXCL12","CXCL14","CCL19","CCL13"), cols = c("grey","red")) + xlab(label = "") + ylab(label = "") + RotatedAxis()
dev.off()
# Stop the clock and print time taken
time_taken<- proc.time() - ptm
print(paste0("Time elapsed: ", sprintf((time_taken[3]/60), fmt = '%#.2f')," minutes"))
```

#Data generation for extended data figure 9c
```{r correlations, warning=FALSE}
# Start the clock!
ptm <- proc.time()
######
#function correlation
######
fn_get_corr_mat <- function(obj, gene_name){
  correlation_df_list<-list()


  mat_count<-as.matrix(obj[['SCT']]@data)
  #hardcoded as spearman change if required
  type<-"spearman"

  #get 'gene of interest' expression of all cells
  count_gene<-mat_count[gene_name,]

  correlation_mat<-matrix(nrow = dim(mat_count)[1], ncol = 2)
  #add rownames
  rownames(correlation_mat) <- rownames(mat_count)
  # Create a nested loop
  for(row in 1:nrow(mat_count)) {
    correlation<-stats::cor.test(count_gene, mat_count[row,], method = type)
    correlation_mat[row,1]<-correlation$estimate
    correlation_mat[row,2]<-correlation$p.value
  }
  correlation_mat<-as.data.frame(correlation_mat)
  colnames(correlation_mat)<-c("corr_estimate","pvalue")
  correlation_mat$gene<-rownames(correlation_mat)
  #discard pvalues greater than 0.05 and correlations below 0.1
  correlation_df<-sqldf::sqldf("SELECT gene, corr_estimate, pvalue
                                FROM correlation_mat
                                WHERE pvalue < 0.05
                                AND corr_estimate > 0.1
                                ORDER BY corr_estimate DESC")

  anti_correlation_df<-sqldf::sqldf("SELECT gene, corr_estimate, pvalue
                                FROM correlation_mat
                                WHERE pvalue < 0.05
                                AND corr_estimate < -0.1
                                ORDER BY corr_estimate ASC")
  correlation_df_list[[paste0("corr_", gene_name)]]<-correlation_df
  correlation_df_list[[paste0("acorr_", gene_name)]]<-anti_correlation_df
  list_corr_mat <- correlation_df_list
  return(list_corr_mat)
}

gene_name<-"CXCL9"

integrated_LC_cohort1<-PrepSCTFindMarkers(integrated_LC_cohort1)

list_corr_mat<-fn_get_corr_mat(integrated_LC_cohort1, gene_name)

head(list_corr_mat[[paste0("corr_", gene_name)]],20)
head(list_corr_mat[[paste0("acorr_", gene_name)]],20)

write.table(list_corr_mat[[paste0("corr_", gene_name)]], file = paste0(save_path,"corr_",gene_name,".csv"), sep=",", row.names = FALSE)

write.table(list_corr_mat[[paste0("acorr_", gene_name)]], file = paste0(save_path, "acorr_",gene_name,".csv"), sep=",", row.names = FALSE)

rm(list_corr_mat)
# Stop the clock and print time taken
time_taken<- proc.time() - ptm
print(paste0("Time elapsed: ", sprintf((time_taken[3]/60), fmt = '%#.2f')," minutes"))
```


CELL2LOCATION BEGINS##############################################################

```{r add cell2location information to metadata}
cell2location_abundances <- read.csv(paste0(save_path, "q05_cell_abundance_w_sf_barcoded.csv"))
rownames(cell2location_abundances)<-cell2location_abundances$spot_id
# [1] "spot_id"             "DC1"                 "DC2"                
#  [4] "DifferentiatedKC"    "DifferentiatedKC_"   "F1"                 
#  [7] "F2"                  "F3"                  "ILC13"              
# [10] "ILC1NK"              "ILC2"                "Infmono"            
# [13] "LC1"                 "LC2"                 "LC3"                
# [16] "LC4"                 "LE1"                 "LE2"                
# [19] "Macro1"              "Macro2"              "Mastcell"           
# [22] "Melanocyte"          "MigDC"               "Mono"               
# [25] "NK"                  "Pericyte1noninflamm" "Pericyte2inflamm"   
# [28] "Plasma"              "ProliferatingKC"     "Schwann1"           
# [31] "Schwann2"            "Tc"                  "Th"                 
# [34] "Treg"                "UndifferentiatedKC_" "VE1"                
# [37] "VE2"                 "VE3"                 "moDC1"              
# [40] "moDC2"               "moDC3"  
cell_types<-colnames(cell2location_abundances)
cell_types<-cell_types[2:length(cell_types)]

df<-cell2location_abundances[,cell_types]#_thresholded

# calculate the maximum of each column - Not applicable for this dataset
df_max <- apply(df, 2, max)
#df_max <- colMaxs(df) requires a package
#df_median <- apply(df, 2, median)
#df_3rd_quantile <- apply(df, 2, function(x) quantile(x, probs = 0.75,na.rm = T))

# sort the dataframe based on the mean values
#df_sorted <- df[, order(df_max, decreasing = T)]
df_sorted <- df[, order(df_max, decreasing = T)]
df_melt <- melt(df_sorted)

#pdf(paste0(save_path, "sorted_all_box_cell2space_sd22.2.1.pdf"), height = 10, width=7)
  ggplot(data = df_melt, aes(x = value, y = variable, fill = variable)) + 
        geom_boxplot() + 
        coord_flip()  + 
        theme_classic() + 
        theme(legend.position="none", axis.text.x = element_text(angle = 90, hjust = 1)) +
        geom_vline(aes(xintercept = quantile(df_max, probs = 0.25,na.rm = T)), col = "red", size = 0.3) +
        ylab(label = "") +
        xlab(label = "Cell2Location q05 abundances")
#dev.off() 
#threshold abundances
subset_df_max <- subset(df_max, df_max>quantile(df_max, probs = 0.25,na.rm = T))
#subset_df_median <- subset(df_median, df_median>mean(df_median))
#subset_df_3rd_quantile <- subset(df_3rd_quantile, df_3rd_quantile>mean(df_3rd_quantile))

######run when not thresholding
#cell2location_abundances <- cell2location_abundances[, cell_types]
#####
#already stored in the rds. Only uncomment when running all over again
#integrated_LC_cohort1<-AddMetaData(integrated_LC_cohort1, metadata = cell2location_abundances_thresholded)
# cluster2only <- AddMetaData(cluster2only, metadata = cell2location_abundances_thresholded)
# cluster7only <-  AddMetaData(cluster7only, metadata = cell2location_abundances_thresholded)
#write.csv(integrated_LC_cohort1@meta.data[, c("integrated_snn_res.0.3", cell_types)], paste0(save_path, "sd22.2.1_cell2location_abundances_by_cluster.csv"))

sd22.2.1_cell2location_abundances_by_cluster <- integrated_LC_cohort1@meta.data[, c("integrated_snn_res.0.3", cell_types)]

avg_sd22.2.1_cell2location_abundances_by_cluster <- aggregate(x= sd22.2.1_cell2location_abundances_by_cluster[, cell_types],
                                                    # Specify group indicator
                                                    by = list(sd22.2.1_cell2location_abundances_by_cluster$integrated_snn_res.0.3),      
                                                    # Specify function (i.e. mean)
                                                    FUN = mean)
print(avg_sd22.2.1_cell2location_abundances_by_cluster)

#write.csv(avg_sd22.2.1_cell2location_abundances_by_cluster, paste0(save_path, "sd22.2.1_cell2location_abundances_by_cluster_AVERAGED.csv"))


```


```{r sorted_box_plots}
lesion_core_celltypes <- c("DC2","Tc","Treg","Melanocyte","Mono","Macro2","LC1","F2","Th","F3","DifferentiatedKC","Macro1","MigDC","DifferentiatedKC.","ILC13","Pericyte2inflamm","F1","Pericyte1noninflamm","ILC1NK","VE1")

integrated_LC_cohort1<-SetIdent(integrated_LC_cohort1, value = "seurat_clusters")
for(identity in c("2","7")){
  obj<-subset(integrated_LC_cohort1, idents = identity)
  df<-obj@meta.data[,cell_types]
  
  # calculate the maximum of each column - Not applicable for this dataset
  #df_max <- apply(df, 2, max)
  #df_max <- colMaxs(df) requires a package
  df_median <- apply(df, 2, median)
  #df_3rd_quantile <- apply(df, 2, function(x) quantile(x, probs = 0.75,na.rm = T))
  
  # sort the dataframe based on the mean values
  #df_sorted <- df[, order(df_max, decreasing = T)]
  df_sorted <- df[, order(df_median, decreasing = T)]
  df_melt <- melt(df_sorted)
  
  pdf(paste0(save_path,"cluster_",identity, "_sorted_all_box_cell2space_sd22.2.1.pdf"), height = 10, width=7)
    plot_cluster  <- ggplot(data = df_melt, aes(x = value, y = variable, fill = variable)) + 
            geom_boxplot() + 
            coord_flip()  + 
            theme_classic() + 
            theme(legend.position="none", axis.text.x = element_text(angle = 90, hjust = 1)) +
            geom_vline(aes(xintercept = quantile(df_median, probs = 0.25,na.rm = T)), col = "red", size = 0.3) +
            scale_x_continuous(limits=c(0, 40), breaks=c(0,10, 20, 30, 40)) +
            ylab(label = "") +
            xlab(label = "Cell2Location q05 abundances")
    print(plot_cluster)
  dev.off() 
  rm(obj)
}

```



```{r corrplot}
#significance
cor.mtest <- function(mat, ...) {
    mat <- as.matrix(mat)
    n <- ncol(mat)
    p.mat<- matrix(NA, n, n)
    diag(p.mat) <- 0
    for (i in 1:(n - 1)) {
        for (j in (i + 1):n) {
            tmp <- cor.test(mat[, i], mat[, j], ...)
            p.mat[i, j] <- p.mat[j, i] <- tmp$p.value
        }
    }
  colnames(p.mat) <- rownames(p.mat) <- colnames(mat)
  p.mat
}
integrated_LC_cohort1_cluster2 <- subset(integrated_LC_cohort1, subset = integrated_snn_res.0.3 == "2")
cell2location_abundances_cluster2<-integrated_LC_cohort1_cluster2@meta.data[, lesion_core_celltypes]
cell2location_abundances_cluster2_corr <- cor(cell2location_abundances_cluster2)
# matrix of the p-value of the correlation
p.mat <- cor.mtest(cell2location_abundances_cluster2)


pdf(paste0(save_path, "FIG5f_cell2space_sd22.2.1_LESION_CORE_spot_correlation.pdf"), height = 10, width=15)
  corrplot(cell2location_abundances_cluster2_corr, type = "upper", 
           p.mat = p.mat, sig.level = 0.05, insig = "blank", tl.col="black", tl.srt=45,
           order="hclust")
  corrplot(cell2location_abundances_cluster2_corr, type = "lower", 
           p.mat = p.mat, sig.level = 0.05, insig = "blank", tl.col="black", tl.srt=45,
           order="hclust")
dev.off()  
```


```{r spatial_maps}
pdf(paste0(save_path, "For_Extended_Data_9b_cell2space_sd22.2.1.pdf"), height = 9, width=15)
  for(image_count in 1:length(integrated_LC_cohort1@images)){
    image<-names(integrated_LC_cohort1@images)[image_count]
    print(SpatialFeaturePlot(integrated_LC_cohort1, features = head(lesion_core_celltypes,10), image.alpha = 0, pt.size.factor = 2, alpha = c(0.1,2), images =image, ncol = 5))
    print(SpatialFeaturePlot(integrated_LC_cohort1, features = tail(lesion_core_celltypes,10), image.alpha = 0, pt.size.factor = 2, alpha = c(0.1,2), images = image, ncol = 5))
  }
dev.off()
```



